### ISSUE TITLE
Increase body font-weight

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#13]
The base font-weight does not anti-alias well, causing eye strain while reading. Please increase from 300 to 400 in app.css.

```css
body {
...
  font-weight: 400;
...
}
```
